public class demoClasOne {
    public void displayValu()
    {
        string name ='abreha';
        integer age=18;
        boolean active= true;
        system.debug('age is' +age);
        system.debug('is he active?'+active);
        system.debug('my name is' +name);
        Long myLongNum= 177766543;
        Double myDoubleNum =234567.98;
        system.debug('my long number is =' +myLongNum);
        system.debug('my double number'+myDoubleNum);
            Date mydate = system.today();
            ID myid ='a018b00000yRMqxAAG';
            object obi= 1243;
            system.debug(mydate);
            system.debug(myid);
            system.debug(obi);
            string fName ='ABREHA';
            string lName='gebreslasie';
            string fullName= fName+' '+lName;
            system.debug( ' My full name is '+fullName);
    }
}