students rep1 = new students();
rep1.firstName ='Alexander';
rep1.lastName='michael';
rep1.clasYear=2022;
rep1.major='Mathematics';
rep1.generalReport();

students rep2 = new students();
rep2.firstName ='Ausman';
rep2.lastName='Nur';
rep2.clasYear=2022;
rep2.major='English';
rep2.generalReport();

students rep3 = new students();
rep3.firstName ='Kibrom';
rep3.lastName='Abebe';
rep3.clasYear=2022;
rep3.major='Computer Science';
rep3.generalReport();