WhileLoopDemo demo = new WhileLoopDemo();
//demo.demowhilr();
//demo.dowhileDemo();
//demo.forloopDemo();
//demo.demoOfOdNum(3,15);
//demo.muLtiplicationTableDemo(34);
//demo.itratiList();
//demo.iterateSet();
//demo.capitalizeDemo();

//demo.mapItrating();
//List<integer> inputList = new List<integer>{10,20,30,40,50,60};
//system.debug('the sum of the numbers in the list is= '+demo.addingNumbeItrat(inputList));
//demo.reversListValu();
//WhileLoopDemo.updateMap();
demo.LargestOfthreeNum();

